---
- name: Ensure Apache is installed on Rocky.
  ansible.builtin.dnf:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"
